# Site settings
title: OSM History
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/osm-history" # the subpath of your site, e.g. /blog/
url: "mikelmaron.github.io" # the base hostname & protocol for your site
twitter_username: mikel
github_username:  mikelmaron

# Build settings
markdown: kramdown
